/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import {
  Search,
  Zap,
  TrendingUp,
  BarChart3,
  Settings,
  Sliders,
  Database,
  Link,
  Lock,
  Save,
  Check,
} from 'lucide-react';
import { AppRoute } from '../types';

interface PlaceholderViewProps {
  route: AppRoute;
  apiBaseUrl: string;
  onUpdateApiUrl: (url: string) => void;
}

export default function PlaceholderView({ route, apiBaseUrl, onUpdateApiUrl }: PlaceholderViewProps) {
  const [localUrl, setLocalUrl] = React.useState(apiBaseUrl);
  const [saved, setSaved] = React.useState(false);

  React.useEffect(() => {
    setLocalUrl(apiBaseUrl);
  }, [apiBaseUrl]);

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();
    onUpdateApiUrl(localUrl);
    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
  };

  switch (route) {
    case 'market-scanner':
      return (
        <div className="space-y-6">
          <div>
            <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
              <Search className="h-5 w-5 text-brand-bybit" />
              <span>Market Scanner</span>
            </h2>
            <p className="text-xs text-slate-500 mt-1">
              Real-time intraday token, order book, and volatility scanner.
            </p>
          </div>

          <div className="rounded-xl border border-trading-border bg-card-bg p-12 text-center max-w-2xl mx-auto mt-6">
            <div className="mx-auto rounded-full bg-dark-bg p-4 text-slate-500 border border-trading-border w-16 h-16 flex items-center justify-center">
              <Search className="h-8 w-8" />
            </div>
            <h3 className="mt-6 text-base font-semibold text-slate-200">Scanner Engine Offline</h3>
            <p className="mt-2 text-xs text-slate-400 leading-relaxed max-w-md mx-auto">
              The Intraday Market Scanner scans multiple Bybit pairs for volume surges and break-outs. Because the backend server is currently not connected, no real-time metrics are available.
            </p>
            <div className="mt-6 rounded-lg bg-dark-bg p-3 border border-trading-border/50 text-[11px] text-slate-500 text-left font-mono max-w-sm mx-auto">
              <span className="text-brand-bybit font-semibold block mb-1">How it works:</span>
              Once online, this scanner parses price action filters and RSI signals on 5m, 15m, and 1h intervals.
            </div>
          </div>
        </div>
      );

    case 'signals':
      return (
        <div className="space-y-6">
          <div>
            <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
              <Zap className="h-5 w-5 text-brand-bybit" />
              <span>Trading Signals</span>
            </h2>
            <p className="text-xs text-slate-500 mt-1">
              Automated buy/sell entry alerts triggered by active trading strategies.
            </p>
          </div>

          <div className="rounded-xl border border-trading-border bg-card-bg p-12 text-center max-w-2xl mx-auto mt-6">
            <div className="mx-auto rounded-full bg-dark-bg p-4 text-slate-500 border border-trading-border w-16 h-16 flex items-center justify-center">
              <Zap className="h-8 w-8" />
            </div>
            <h3 className="mt-6 text-base font-semibold text-slate-200">No Active Signals</h3>
            <p className="mt-2 text-xs text-slate-400 leading-relaxed max-w-md mx-auto">
              Signals generated by indicators (MACD crossovers, Bollinger Bands breakout, and custom order flow metrics) will reside in this portal. Connecting the backend is required.
            </p>
            <div className="mt-6 rounded-lg bg-dark-bg p-3 border border-trading-border/50 text-[11px] text-slate-500 text-left font-mono max-w-sm mx-auto">
              <span className="text-brand-bybit font-semibold block mb-1">Technical Specs:</span>
              Provides execution recommendations with precise Stop Loss (SL), Take Profit (TP), and Leverage levels.
            </div>
          </div>
        </div>
      );

    case 'active-trades':
      return (
        <div className="space-y-6">
          <div>
            <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
              <TrendingUp className="h-5 w-5 text-brand-bybit" />
              <span>Active Trades</span>
            </h2>
            <p className="text-xs text-slate-500 mt-1">
              Active positions, leverage management, and trailing take-profit tracking.
            </p>
          </div>

          <div className="rounded-xl border border-trading-border bg-card-bg p-12 text-center max-w-2xl mx-auto mt-6">
            <div className="mx-auto rounded-full bg-dark-bg p-4 text-slate-500 border border-trading-border w-16 h-16 flex items-center justify-center">
              <TrendingUp className="h-8 w-8" />
            </div>
            <h3 className="mt-6 text-base font-semibold text-slate-200">No Positions Opened</h3>
            <p className="mt-2 text-xs text-slate-400 leading-relaxed max-w-md mx-auto">
              Active intraday trade parameters (Entry Price, Size, Current P&L, Liquidation Price) are hidden because the executor is not running. 
            </p>
            <div className="mt-6 rounded-lg bg-dark-bg p-3 border border-trading-border/50 text-[11px] text-slate-500 text-left font-mono max-w-sm mx-auto flex items-center gap-2 justify-center">
              <span className="h-2 w-2 rounded-full bg-rose-500 shrink-0"></span>
              <span className="font-semibold text-slate-400">Execution Engine Offline: 0 Trades Connected</span>
            </div>
          </div>
        </div>
      );

    case 'performance':
      return (
        <div className="space-y-6">
          <div>
            <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
              <BarChart3 className="h-5 w-5 text-brand-bybit" />
              <span>Performance Analysis</span>
            </h2>
            <p className="text-xs text-slate-500 mt-1">
              Historical statistics, Win/Loss ratios, Sharpe ratios, and trading metrics.
            </p>
          </div>

          <div className="rounded-xl border border-trading-border bg-card-bg p-12 text-center max-w-2xl mx-auto mt-6">
            <div className="mx-auto rounded-full bg-dark-bg p-4 text-slate-500 border border-trading-border w-16 h-16 flex items-center justify-center">
              <BarChart3 className="h-8 w-8" />
            </div>
            <h3 className="mt-6 text-base font-semibold text-slate-200">No Analytical Logs Recorded</h3>
            <p className="mt-2 text-xs text-slate-400 leading-relaxed max-w-md mx-auto">
              Detailed performance metrics (Drawdown, consecutive wins/losses, daily profits, and commission costs) will populate here as the demo bot places and concludes trades.
            </p>
            <div className="mt-6 flex flex-wrap justify-center gap-4 text-center text-xs text-slate-500 font-mono">
              <div className="border border-trading-border bg-dark-bg/45 px-3 py-1.5 rounded-lg">Win Rate: 0.0%</div>
              <div className="border border-trading-border bg-dark-bg/45 px-3 py-1.5 rounded-lg">Profit Factor: 0.00</div>
              <div className="border border-trading-border bg-dark-bg/45 px-3 py-1.5 rounded-lg">Avg Trade: 0.00 USDT</div>
            </div>
          </div>
        </div>
      );

    case 'settings':
      return (
        <div className="space-y-6 max-w-4xl">
          <div>
            <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
              <Settings className="h-5 w-5 text-brand-bybit" />
              <span>Settings</span>
            </h2>
            <p className="text-xs text-slate-500 mt-1">
              Configure system parameters, API variables, and server connections.
            </p>
          </div>

          {/* Connection Settings */}
          <div className="rounded-xl border border-trading-border bg-card-bg p-5 shadow-sm space-y-4">
            <div className="flex items-center gap-2 border-b border-trading-border pb-3">
              <Sliders className="h-4.5 w-4.5 text-brand-bybit" />
              <h3 className="font-semibold text-slate-100 text-sm">System Connection</h3>
            </div>

            <form onSubmit={handleSave} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-400 mb-1.5">
                  VITE_API_BASE_URL (Backend Server Endpoint)
                </label>
                <div className="relative">
                  <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none text-slate-500">
                    <Link className="h-4 w-4" />
                  </div>
                  <input
                    type="url"
                    value={localUrl}
                    onChange={(e) => setLocalUrl(e.target.value)}
                    placeholder="https://api.your-bybit-bot-backend.com"
                    className="block w-full rounded-lg border border-trading-border bg-dark-bg pl-10 pr-4 py-2.5 text-sm font-mono text-slate-100 placeholder-slate-600 focus:border-brand-bybit focus:ring-1 focus:ring-brand-bybit focus:outline-none transition-all"
                  />
                </div>
                <p className="text-[11px] text-slate-500 mt-1.5 leading-relaxed">
                  The frontend bot targets this URL to check API status, trigger execution loops, fetch live signals, and inspect open positions. Use `https://your-server.com/api` or local machine parameters.
                </p>
              </div>

              <div className="flex justify-end pt-2">
                <button
                  type="submit"
                  className="inline-flex items-center gap-2 rounded-lg bg-brand-bybit hover:bg-brand-bybit/90 text-slate-950 px-4 py-2 text-xs font-semibold transition-colors cursor-pointer shadow-md shadow-brand-bybit/10"
                >
                  {saved ? (
                    <>
                      <Check className="h-4 w-4" />
                      <span>Saved Connection</span>
                    </>
                  ) : (
                    <>
                      <Save className="h-4 w-4" />
                      <span>Save Config</span>
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>

          {/* Credentials Info - Read Only */}
          <div className="rounded-xl border border-trading-border bg-card-bg p-5 shadow-sm space-y-4">
            <div className="flex items-center gap-2 border-b border-trading-border pb-3">
              <Lock className="h-4.5 w-4.5 text-brand-bybit" />
              <h3 className="font-semibold text-slate-100 text-sm">Security & Exchange Credentials</h3>
            </div>

            <div className="rounded-lg bg-dark-bg p-4 border border-trading-border/50">
              <div className="flex items-center gap-2.5">
                <div className="rounded-md bg-dark-bg p-1.5 text-slate-500 border border-trading-border">
                  <Database className="h-4 w-4" />
                </div>
                <div>
                  <h4 className="text-xs font-semibold text-slate-300">Bybit Demo Exchange Keys</h4>
                  <p className="text-[10px] text-slate-500 mt-0.5">
                    For maximum security, API keys (API Key & Private Secret) are never handled client-side. They must be stored as environment variables on your server backend.
                  </p>
                </div>
              </div>

              <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                <div className="rounded-lg bg-card-bg p-3 border border-trading-border/55 flex items-center justify-between">
                  <span className="text-slate-500 font-semibold">BYBIT_DEMO_API_KEY</span>
                  <span className="text-slate-400 font-mono text-[10px]">Configured Server-Side</span>
                </div>
                <div className="rounded-lg bg-card-bg p-3 border border-trading-border/55 flex items-center justify-between">
                  <span className="text-slate-500 font-semibold">BYBIT_DEMO_SECRET</span>
                  <span className="text-slate-400 font-mono text-[10px]">Configured Server-Side</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      );

    default:
      return null;
  }
}
